module.exports = {
  name: 'inspire',
  shortcut: ['quote'],
  description: 'Send an inspirational quote generated by Inspirobot AI',
  usage: '!inspire',
  async execute (Discord, message, args, client) {
    const axios = require('axios');
    const result = await axios.get('https://inspirobot.me/api?generate=true');
    message.channel.send(result.data);
  }
};
