module.exports = {
  name: 'inspire',
  aliases: ['quote'],
  description: 'Send an inspirational quote generated by Inspirobot AI',
  usage: '!inspire',
  async execute (Discord, message, args, client) {
    const axios = require('axios');
    const result = await axios.get('https://inspirobot.me/api?generate=true');
    const inspirobotEmbed = new Discord.MessageEmbed()
      .setColor(message.guild.me.displayHexColor)
      .setImage(result.data)
      .setFooter('Courtesy of Inspirobot © - 2020');
    message.channel.send(inspirobotEmbed);
  }
};
